### ISSUE TITLE
Internal metadata formatting

### ISSUE THREAD

**Issue by Tumultuous-RGR-SiM** [anonymous-archiver/pastebin-dl#2]
This is another non-critical issue, but the metadata inside the file itself could be touched up a bit.

- The paste title doesn't need quotation marks around it
- The semicolon between [By: AUTHOR] shouldn't be there
- There should be a blank line between the author's byline and the link to their pastebin
- The link to the specific paste should be to the normal paste, not the raw (This one is really nitpicky, I know)
- The data formatting is strange. 
-- Friday, in the last edit section is written out in longform, but "Sat" in the retrieved section is written out in truncated form
-- Four spaces in between the retrieved date and the beginning of the paste is a bit excessive. Could this be cut down to three? (again, nitpicking)

**Comment by anonymous-archiver** [comment]
Sure, I can futz with the metadata.  All that stuff was just lazily crammed into the file.

**Comment by anonymous-archiver** [comment]
Ok, just put out a new release with all the suggestions you made.  Marking as closed.
