### ISSUE TITLE
Ampersand (&) in filename being deleted

### ISSUE THREAD

**Issue by Tumultuous-RGR-SiM** [anonymous-archiver/pastebin-dl#3]
The Ampersands (&) that Cee-esS sometimes adds to his pastes are being deleted. That turns a paste that has "15&16" into "1516".

I suggest replacing the & with the word "and", since most people would probably use it with spaces, like "15 & 16".

**Comment by anonymous-archiver** [comment]
Yep, simple enough to fix.  Give me a few min.
